Fix Travis CI configuration
costela/wile pull request #26
Opened 2017-08-24 13:26 UTC by ivuk

Currently, Travis CI fails to test Python 3.5 and Python 3.6 (on GNU/Linux) properly.

These two commits fix the Python 3.{5,6} tests on GNU/Linux. They also switch the default environment that Travis uses to Trusty, per Travis' recommendations.

Hope you're having a great day! :)

2017-08-24 14:11 UTC, costela requested changes
Thanks a lot for spotting this problem! Embarrassing! :sweat_smile: 
Unfortunately I must admit I'm not a big fan of big verbose `.travis.yml` files. Wouldn't it be more concise to use something like this on the top-level?
```
env: TOXENV=py36,py35,py34,py27
python:
  - '3.6'
  - '3.5'
  - '3.4'
  - '2.7'
matrix:
  include:
    - env: TOXENV=flake8
```
Not sure this works as I imagine, but we can give it a try.

Maybe you could even go ahead and add
```
matrix:
  fast_finish: true
```
OSX tests are totally broken anyway... :wink:

2017-08-24 14:11 UTC, costela commented on .travis.yml
> +      dist: trusty
Wouldn't it be cleaner to set `dist: trusty` on the top-level? Am I missing something?

2017-08-24 14:11 UTC, costela commented on .travis.yml
> +      sudo: false
...same thing for sudo.

2017-08-25 11:44 UTC, costela requested changes

2017-08-25 11:44 UTC, costela commented on .travis.yml
> +    - env: TOXENV=py27
Maybe we can try setting `TOXENV=py` globally? That could make it use only the default python (avoiding the duplicate tests we were getting with the previous versions). Not sure, but worth a try :wink:

2017-08-25 12:00 UTC, ivuk commented
I don't really see a nice way to avoid unrolling the build matrix at this point. It seems other projects, such as `pip` or `simplejson`, also use the complete matrix specified by hand. I guess it's the easiest way to make Travis get the proper environment variables for a specific interpreter version.

I'll try to work around this a bit more, but at this time I feel that the most we can do is abstract the `dist` and `sudo` variables from the matrix itself.

2017-08-25 12:03 UTC, costela commented
I have one last idea. Give me a second.

2017-08-25 12:22 UTC, costela commented
OK, I think I got it. Before I merge, maybe you'd like to squash a few of your test commits? (you'll probably have to pull, since I pushed to your branched)
Thanks again for the help! :smiley: :+1:

2017-08-25 12:36 UTC, ivuk commented
I guess this should be OK now. :)

2017-08-25 13:00 UTC, costela approved these changes

2017-08-25 13:00 UTC, merged

2017-08-25 13:01 UTC, costela commented
Perfect, thanks! :smiley: :+1: